package resources

object ResString {
    const val APP_NAME: String = "NotifyMock"
    const val saveScheme: String = "Save scheme"
    const val saveAsScheme: String = "Save as scheme"
    const val falseString: String = "false"
    const val trueString: String = "true"
    const val changeType: String = "Change type"
    const val console: String = "Console output"
    const val clear: String = "Clear"
    const val run: String = "Run"
    const val remove: String = "Remove"
    const val loading: String = "Loading"
    const val keyLabel: String = "Key"
    const val valueLabel: String = "Value"
    const val error: String = "Error"
    const val emptyError: String = "Empty data!"
    const val packageLabel: String = "Package"
    const val intentLabel: String = "Intent"
    const val addParam: String = "Add param"
    const val file: String = "File"
    const val loadScheme: String = "Open scheme"
    const val about: String = "About"
    const val faq: String = "FAQ"
    const val help: String = "Help"
    const val consoleOutput: String = "Console"
    const val ok: String = "OK"
    const val cancel: String = "Cancel"
}